name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create Capacitor project
        run: |
          mkdir -p www
          cp index.html www/index.html

          npm init -y

          npm install @capacitor/core@7.4.4 @capacitor/android@7.4.4
          npm install -D @capacitor/cli@7.4.4

          npx cap init "My HTML App" "com.example.myhtmlapp" --web-dir=www
          npx cap add android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-HTML-App-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
